### ISSUE TITLE
Push to Heroku

### ISSUE THREAD

**Issue by benjstorlie** [benjstorlie/sudoku-shuffle#43]
We should be able to to this now.

**Comment by benjstorlie** [comment]
[Guide to Deploy with Heroku and MongoDB Atlas on the Full-Stack Blog](https://coding-boot-camp.github.io/full-stack/mongodb/deploy-with-heroku-and-mongodb-atlas)

**Comment by PatrickWLowe** [comment]
Heroku deployed
