### ISSUE TITLE
Integrate External API for Game Data

### ISSUE THREAD

**Issue by benjstorlie** [benjstorlie/sudoku-shuffle#5]
Fetch game data from an external API and integrate it into the app.

https://sudoku-api.vercel.app/

It says it's powered by GraphQL.  How do you search for a specific difficulty?

Still, you could just keep asking the API until you get one with the desired difficulty.

**Comment by npcoiner** [comment]
Fetch game data complete on the branch. Attempts to get a board 3 times that hopefully matches the desired difficulty, then defaults to a template if it can't.

**Comment by npcoiner** [comment]
The current board data returned is formatted as an object. Now working on adding extra functions to get specifics from the object, like array data, formatted similarly to gridArr().
